//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace getUserInfo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JINJIEntities1 : DbContext
    {
        public JINJIEntities1()
            : base("name=JINJIEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<V_PERSON_OF_COMPANY> V_PERSON_OF_COMPANY { get; set; }
        public virtual DbSet<V_PERSON_OF_OTHER_COMPANY> V_PERSON_OF_OTHER_COMPANY { get; set; }
    }
}
