//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace getUserInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RETURN_ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RETURN_ITEM()
        {
            this.REPLY_PERMISSION = new HashSet<REPLY_PERMISSION>();
        }
    
        public byte RETURN_ITEM_CODE { get; set; }
        public string RETURN_TABLE_NAME { get; set; }
        public string RETURN_ITEM_NAME { get; set; }
        public bool DELETE_FLAG { get; set; }
        public string DELETE_HOST_NAME { get; set; }
        public Nullable<System.DateTime> DELETE_DATE_TIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPLY_PERMISSION> REPLY_PERMISSION { get; set; }
    }
}
