//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace getUserInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PERSON_OF_COMPANY
    {
        public string STAFF_CODE { get; set; }
        public string KANJI_NAME { get; set; }
        public string ROMAN_NAME { get; set; }
        public string KANA_NAME { get; set; }
        public string ORIGINAL_NAME_FLAG { get; set; }
        public string KANJI_ORIGINAL_NAME { get; set; }
        public string ROMAN_ORIGINAL_NAME { get; set; }
        public string KANA_ORIGINAL_NAME { get; set; }
        public string MEN_OR_WOMEN { get; set; }
        public string STAFF_DIVISION_CODE { get; set; }
        public string STAFF_DIVISION_NAME { get; set; }
        public string BELONGING_LATEST_START_DATE { get; set; }
        public string BELONGING_LATEST_CODE { get; set; }
        public string BBL_BU_CODE { get; set; }
        public string BBL_START_VALIDITY_DATE { get; set; }
        public string BBL_END_VALIDITY_DATE { get; set; }
        public string BBL_BU_NAME_1 { get; set; }
        public string BBL_BU_NAME_2 { get; set; }
        public string BBL_BU_NAME_3 { get; set; }
        public string BBL_BU_INFORMAL_NAME { get; set; }
        public string BBL_BU_ALTERATION_MARK { get; set; }
        public string BBL_SECTION_CODE { get; set; }
        public string BBL_BU_LOCATION_CODE { get; set; }
        public string BBL_BU_NUMBER { get; set; }
        public string BBL_EXECUTIVE_NUMBER { get; set; }
        public string BBL_SHITSU_PERSON_SECTION { get; set; }
        public string BBL_ADJUST_SECTION_NUMBER_A { get; set; }
        public string BBL_ADJUST_SECTION_NUMBER_B { get; set; }
        public string BBL_ADJUST_SECTION_NUMBER_C { get; set; }
        public string BBL_ADJUST_SECTION_NUMBER_D { get; set; }
        public string BBL_ASSESSMENT_CODE { get; set; }
        public string BBL_RANK_RISE_CODE { get; set; }
        public string BBL_CHANGE_CODE { get; set; }
        public string BBL_TRAINING_CODE { get; set; }
        public string BBL_EMPLOY_OFFICE_CODE { get; set; }
        public string BBL_NEW_BELONGING_LIMIT_FLAG { get; set; }
        public string BBL_PERSONNEL_EXCEPTION { get; set; }
        public string BBL_PERSONNEL_COMPULSION { get; set; }
        public string BBL_ENGLISH_NAME { get; set; }
        public string SBL_SHITSU_CODE { get; set; }
        public string SBL_START_VALIDITY_DATE { get; set; }
        public string SBL_END_VALIDITY_DATE { get; set; }
        public string SBL_BU_CODE { get; set; }
        public string SBL_BU_NAME_1 { get; set; }
        public string SBL_BU_NAME_2 { get; set; }
        public string SBL_BU_INFORMAL_NAME { get; set; }
        public string SBL_SHITSU_NAME { get; set; }
        public string SBL_SHITSU_INFORMAL_NAME { get; set; }
        public string SBL_SHITSU_CHANGE_MARK { get; set; }
        public string SBL_SHITSU_LOCATION_CODE { get; set; }
        public string SBL_SHITSU_KA_NUMBER { get; set; }
        public string SBL_SHITSU_KA_DIVISION_CODE { get; set; }
        public string SBL_NEW_BELONGING_LIMIT_FLAG { get; set; }
        public string SBL_ENGLISH_NAME { get; set; }
        public string KBL_KAKARI_CODE { get; set; }
        public string KBL_START_VALIDITY_DATE { get; set; }
        public string KBL_END_VALIDITY_DATE { get; set; }
        public string KBL_BU_CODE { get; set; }
        public string KBL_SHITSU_CODE { get; set; }
        public string KBL_BU_NAME_1 { get; set; }
        public string KBL_BU_NAME_2 { get; set; }
        public string KBL_BU_INFORMAL_NAME { get; set; }
        public string KBL_SHITSU_NAME { get; set; }
        public string KBL_SHITSU_INFORMAL_NAME { get; set; }
        public string KBL_KAKARI_NAME { get; set; }
        public string KBL_KAKARI_INFORMAL_NAME { get; set; }
        public string KBL_KAKARI_LOCATION_CODE { get; set; }
        public string KBL_KAKARI_NUMBER { get; set; }
        public string KBL_KAKARI_DIVISION_CODE { get; set; }
        public string KBL_NEW_BELONGING_LIMIT_FLAG { get; set; }
        public string BELONGING_LATEST_BU_NAME { get; set; }
        public string BELONGING_LATEST_SHITSU_NAME { get; set; }
        public string BELONGING_LATEST_KAKARI_NAME { get; set; }
        public string LOCATION_CODE { get; set; }
        public string LOCATION_NAME { get; set; }
        public string COMPANY_CODE { get; set; }
        public string INFORMAL_COMPANY_NAME { get; set; }
        public string JOB_CATEGORY_CODE { get; set; }
        public string JOB_CATEGORY_NAME { get; set; }
        public string QUALIFICATION_SYSTEM_CODE { get; set; }
        public string QUALIFICATION_CODE { get; set; }
        public string ORIGINAL_BELONGING_FLAG { get; set; }
        public string ORIGINAL_BELONGING_START_DATE { get; set; }
        public string ORIGINAL_BELONGING_CODE { get; set; }
        public string BOB_BU_CODE { get; set; }
        public string BOB_START_VALIDITY_DATE { get; set; }
        public string BOB_END_VALIDITY_DATE { get; set; }
        public string BOB_BU_NAME_1 { get; set; }
        public string BOB_BU_NAME_2 { get; set; }
        public string BOB_BU_NAME_3 { get; set; }
        public string BOB_BU_INFORMAL_NAME { get; set; }
        public string BOB_BU_ALTERATION_MARK { get; set; }
        public string BOB_SECTION_CODE { get; set; }
        public string BOB_BU_LOCATION_CODE { get; set; }
        public string BOB_BU_NUMBER { get; set; }
        public string BOB_EXECUTIVE_NUMBER { get; set; }
        public string BOB_SHITSU_PERSON_SECTION { get; set; }
        public string BOB_ADJUST_SECTION_NUMBER_A { get; set; }
        public string BOB_ADJUST_SECTION_NUMBER_B { get; set; }
        public string BOB_ADJUST_SECTION_NUMBER_C { get; set; }
        public string BOB_ADJUST_SECTION_NUMBER_D { get; set; }
        public string BOB_ASSESSMENT_CODE { get; set; }
        public string BOB_RANK_RISE_CODE { get; set; }
        public string BOB_CHANGE_CODE { get; set; }
        public string BOB_TRAINING_CODE { get; set; }
        public string BOB_EMPLOY_OFFICE_CODE { get; set; }
        public string BOB_NEW_BELONGING_LIMIT_FLAG { get; set; }
        public string BOB_PERSONNEL_EXCEPTION { get; set; }
        public string BOB_PERSONNEL_COMPULSION { get; set; }
        public string BOB_ENGLISH_NAME { get; set; }
        public string SOB_SHITSU_CODE { get; set; }
        public string SOB_START_VALIDITY_DATE { get; set; }
        public string SOB_END_VALIDITY_DATE { get; set; }
        public string SOB_BU_CODE { get; set; }
        public string SOB_BU_NAME_1 { get; set; }
        public string SOB_BU_NAME_2 { get; set; }
        public string SOB_BU_INFORMAL_NAME { get; set; }
        public string SOB_SHITSU_NAME { get; set; }
        public string SOB_SHITSU_INFORMAL_NAME { get; set; }
        public string SOB_SHITSU_CHANGE_MARK { get; set; }
        public string SOB_SHITSU_LOCATION_CODE { get; set; }
        public string SOB_SHITSU_KA_NUMBER { get; set; }
        public string SOB_SHITSU_KA_DIVISION_CODE { get; set; }
        public string SOB_NEW_BELONGING_LIMIT_FLAG { get; set; }
        public string SOB_ENGLISH_NAME { get; set; }
        public string KOB_KAKARI_CODE { get; set; }
        public string KOB_START_VALIDITY_DATE { get; set; }
        public string KOB_END_VALIDITY_DATE { get; set; }
        public string KOB_BU_CODE { get; set; }
        public string KOB_SHITSU_CODE { get; set; }
        public string KOB_BU_NAME_1 { get; set; }
        public string KOB_BU_NAME_2 { get; set; }
        public string KOB_BU_INFORMAL_NAME { get; set; }
        public string KOB_SHITSU_NAME { get; set; }
        public string KOB_SHITSU_INFORMAL_NAME { get; set; }
        public string KOB_KAKARI_NAME { get; set; }
        public string KOB_KAKARI_INFORMAL_NAME { get; set; }
        public string KOB_KAKARI_LOCATION_CODE { get; set; }
        public string KOB_KAKARI_NUMBER { get; set; }
        public string KOB_KAKARI_DIVISION_CODE { get; set; }
        public string KOB_NEW_BELONGING_LIMIT_FLAG { get; set; }
        public string ABOUT_WORK_CODE { get; set; }
        public string ABOUT_WORK_NAME { get; set; }
        public string APPROVAL_RANK_CODE { get; set; }
        public string LAYOFF_FLAG { get; set; }
        public string NONREGULAR_DIVISION_NAME { get; set; }
    }
}
