//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace getUserInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PERSON_OF_OTHER_COMPANY
    {
        public string STAFF_CODE { get; set; }
        public string KANJI_NAME { get; set; }
        public string ROMAN_NAME { get; set; }
        public string KANA_NAME { get; set; }
        public string STAFF_DIVISION_CODE { get; set; }
        public string ACCEPTANCE_BELONGING_CODE { get; set; }
        public string BAB_BU_CODE { get; set; }
        public string BAB_START_VALIDITY_DATE { get; set; }
        public string BAB_END_VALIDITY_DATE { get; set; }
        public string BAB_BU_NAME_1 { get; set; }
        public string BAB_BU_NAME_2 { get; set; }
        public string BAB_BU_NAME_3 { get; set; }
        public string BAB_BU_INFORMAL_NAME { get; set; }
        public string BAB_BU_ALTERATION_MARK { get; set; }
        public string BAB_SECTION_CODE { get; set; }
        public string BAB_BU_LOCATION_CODE { get; set; }
        public string BAB_BU_NUMBER { get; set; }
        public string BAB_EXECUTIVE_NUMBER { get; set; }
        public string BAB_SHITSU_PERSON_SECTION { get; set; }
        public string BAB_ADJUST_SECTION_NUMBER_A { get; set; }
        public string BAB_ADJUST_SECTION_NUMBER_B { get; set; }
        public string BAB_ADJUST_SECTION_NUMBER_C { get; set; }
        public string BAB_ADJUST_SECTION_NUMBER_D { get; set; }
        public string BAB_ASSESSMENT_CODE { get; set; }
        public string BAB_RANK_RISE_CODE { get; set; }
        public string BAB_CHANGE_CODE { get; set; }
        public string BAB_TRAINING_CODE { get; set; }
        public string BAB_EMPLOY_OFFICE_CODE { get; set; }
        public string BAB_NEW_BELONGING_LIMIT_FLAG { get; set; }
        public string BAB_PERSONNEL_EXCEPTION { get; set; }
        public string BAB_PERSONNEL_COMPULSION { get; set; }
        public string BAB_ENGLISH_NAME { get; set; }
        public string SAB_SHITSU_CODE { get; set; }
        public string SAB_START_VALIDITY_DATE { get; set; }
        public string SAB_END_VALIDITY_DATE { get; set; }
        public string SAB_BU_CODE { get; set; }
        public string SAB_BU_NAME_1 { get; set; }
        public string SAB_BU_NAME_2 { get; set; }
        public string SAB_BU_INFORMAL_NAME { get; set; }
        public string SAB_SHITSU_NAME { get; set; }
        public string SAB_SHITSU_INFORMAL_NAME { get; set; }
        public string SAB_SHITSU_CHANGE_MARK { get; set; }
        public string SAB_SHITSU_LOCATION_CODE { get; set; }
        public string SAB_SHITSU_KA_NUMBER { get; set; }
        public string SAB_SHITSU_KA_DIVISION_CODE { get; set; }
        public string SAB_NEW_BELONGING_LIMIT_FLAG { get; set; }
        public string SAB_ENGLISH_NAME { get; set; }
        public string KAB_KAKARI_CODE { get; set; }
        public string KAB_START_VALIDITY_DATE { get; set; }
        public string KAB_END_VALIDITY_DATE { get; set; }
        public string KAB_BU_CODE { get; set; }
        public string KAB_SHITSU_CODE { get; set; }
        public string KAB_BU_NAME_1 { get; set; }
        public string KAB_BU_NAME_2 { get; set; }
        public string KAB_BU_INFORMAL_NAME { get; set; }
        public string KAB_SHITSU_NAME { get; set; }
        public string KAB_SHITSU_INFORMAL_NAME { get; set; }
        public string KAB_KAKARI_NAME { get; set; }
        public string KAB_KAKARI_INFORMAL_NAME { get; set; }
        public string KAB_KAKARI_LOCATION_CODE { get; set; }
        public string KAB_KAKARI_NUMBER { get; set; }
        public string KAB_KAKARI_DIVISION_CODE { get; set; }
        public string KAB_NEW_BELONGING_LIMIT_FLAG { get; set; }
        public string START_CONTRACT_TERM { get; set; }
        public string END_CONTRACT_TERM { get; set; }
        public string WORKING_PLACE_CODE { get; set; }
        public string BELONGING_LATEST_CODE { get; set; }
        public string BBL_BU_CODE { get; set; }
        public string BBL_START_VALIDITY_DATE { get; set; }
        public string BBL_END_VALIDITY_DATE { get; set; }
        public string BBL_BU_NAME_1 { get; set; }
        public string BBL_BU_NAME_2 { get; set; }
        public string BBL_BU_NAME_3 { get; set; }
        public string BBL_BU_INFORMAL_NAME { get; set; }
        public string BBL_BU_ALTERATION_MARK { get; set; }
        public string BBL_SECTION_CODE { get; set; }
        public string BBL_BU_LOCATION_CODE { get; set; }
        public string BBL_BU_NUMBER { get; set; }
        public string BBL_EXECUTIVE_NUMBER { get; set; }
        public string BBL_SHITSU_PERSON_SECTION { get; set; }
        public string BBL_ADJUST_SECTION_NUMBER_A { get; set; }
        public string BBL_ADJUST_SECTION_NUMBER_B { get; set; }
        public string BBL_ADJUST_SECTION_NUMBER_C { get; set; }
        public string BBL_ADJUST_SECTION_NUMBER_D { get; set; }
        public string BBL_ASSESSMENT_CODE { get; set; }
        public string BBL_RANK_RISE_CODE { get; set; }
        public string BBL_CHANGE_CODE { get; set; }
        public string BBL_TRAINING_CODE { get; set; }
        public string BBL_EMPLOY_OFFICE_CODE { get; set; }
        public string BBL_NEW_BELONGING_LIMIT_FLAG { get; set; }
        public string BBL_PERSONNEL_EXCEPTION { get; set; }
        public string BBL_PERSONNEL_COMPULSION { get; set; }
        public string BBL_ENGLISH_NAME { get; set; }
        public string SBL_SHITSU_CODE { get; set; }
        public string SBL_START_VALIDITY_DATE { get; set; }
        public string SBL_END_VALIDITY_DATE { get; set; }
        public string SBL_BU_CODE { get; set; }
        public string SBL_BU_NAME_1 { get; set; }
        public string SBL_BU_NAME_2 { get; set; }
        public string SBL_BU_INFORMAL_NAME { get; set; }
        public string SBL_SHITSU_NAME { get; set; }
        public string SBL_SHITSU_INFORMAL_NAME { get; set; }
        public string SBL_SHITSU_CHANGE_MARK { get; set; }
        public string SBL_SHITSU_LOCATION_CODE { get; set; }
        public string SBL_SHITSU_KA_NUMBER { get; set; }
        public string SBL_SHITSU_KA_DIVISION_CODE { get; set; }
        public string SBL_NEW_BELONGING_LIMIT_FLAG { get; set; }
        public string SBL_ENGLISH_NAME { get; set; }
        public string KBL_KAKARI_CODE { get; set; }
        public string KBL_START_VALIDITY_DATE { get; set; }
        public string KBL_END_VALIDITY_DATE { get; set; }
        public string KBL_BU_CODE { get; set; }
        public string KBL_SHITSU_CODE { get; set; }
        public string KBL_BU_NAME_1 { get; set; }
        public string KBL_BU_NAME_2 { get; set; }
        public string KBL_BU_INFORMAL_NAME { get; set; }
        public string KBL_SHITSU_NAME { get; set; }
        public string KBL_SHITSU_INFORMAL_NAME { get; set; }
        public string KBL_KAKARI_NAME { get; set; }
        public string KBL_KAKARI_INFORMAL_NAME { get; set; }
        public string KBL_KAKARI_LOCATION_CODE { get; set; }
        public string KBL_KAKARI_NUMBER { get; set; }
        public string KBL_KAKARI_DIVISION_CODE { get; set; }
        public string KBL_NEW_BELONGING_LIMIT_FLAG { get; set; }
        public string ORIGINAL_CONTRACTOR_CODE { get; set; }
        public string ORIGINAL_CONTRACTOR_NAME { get; set; }
        public string BELONGING_COMPANY_CODE { get; set; }
        public string BELONGING_COMPANY_NAME { get; set; }
        public string CARD_STATUS { get; set; }
    }
}
